name: ta_scanner

channels:
    - default

dependencies:
    - python=3.7
    - click
    - pandas >= 1.0.0    
    - numpy
    - matplotlib
    - tensorflow < 2.0
    # test resources
    - pytest
    - pip
    - pip:
        - ipdb
        - loguru
        - gym
        - black
        - stable_baselines[mpi]
        # testing resources
